In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('heart.csv')

In [4]:
df.shape

(303, 14)

In [5]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
scale.fit(df)
df1 = pd.DataFrame(scale.transform(df), columns=df.columns)
df1.index = df.index
df1.head()

age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1 -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2 -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3  0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4  0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   

    thalach     exang   oldpeak     slope        ca      thal    target  
0  0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  0.914529  
1  1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  0.914529  
2  0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  0.914529  
3  1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  0.914529  
4  0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922  0.914529

In [6]:
df1.describe()

age           sex            cp      trestbps          chol  \
count  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02   
mean   5.825923e-17 -1.319077e-17 -5.562565e-17 -7.146832e-16 -9.828955e-17   
std    1.001654e+00  1.001654e+00  1.001654e+00  1.001654e+00  1.001654e+00   
min   -2.797624e+00 -1.468418e+00 -9.385146e-01 -2.148802e+00 -2.324160e+00   
25%   -7.572802e-01 -1.468418e+00 -9.385146e-01 -6.638668e-01 -6.814943e-01   
50%    6.988599e-02  6.810052e-01  3.203122e-02 -9.273778e-02 -1.210553e-01   
75%    7.316189e-01  6.810052e-01  1.002577e+00  4.783913e-01  5.456738e-01   
max    2.496240e+00  6.810052e-01  1.973123e+00  3.905165e+00  6.140401e+00   

                fbs       restecg       thalach         exang       oldpeak  \
count  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02   
mean  -3.664102e-19  2.652810e-16 -5.203025e-16 -5.203025e-16 -3.140136e-16   
std    1.001654e+00  1.001654e+00  1.001654e+00  1.001654e+00  1.001654e+00   
min   -4.176345e-01 -1.005832e+00 -3.439267e+00 -6.966305e-01 -8.968617e-01   
25%   -4.176345e-01 -1.005832e+00 -7.061105e-01 -6.966305e-01 -8.968617e-01   
50%   -4.176345e-01  8.989622e-01  1.466343e-01 -6.966305e-01 -2.067053e-01   
75%   -4.176345e-01  8.989622e-01  7.151309e-01  1.435481e+00  4.834512e-01   
max    2.394438e+00  2.803756e+00  2.289429e+00  1.435481e+00  4.451851e+00   

              slope            ca          thal        target  
count  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02  
mean   1.355718e-16  4.752341e-16  3.484561e-16  7.577364e-16  
std    1.001654e+00  1.001654e+00  1.001654e+00  1.001654e+00  
min   -2.274579e+00 -7.144289e-01 -3.784824e+00 -1.093459e+00  
25%   -6.491132e-01 -7.144289e-01 -5.129219e-01 -1.093459e+00  
50%   -6.491132e-01 -7.144289e-01 -5.129219e-01  9.145292e-01  
75%    9.763521e-01  2.650822e-01  1.123029e+00  9.145292e-01  
max    9.763521e-01  3.203615e+00  1.123029e+00  9.145292e-01

In [7]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# Why drop target - otherwise it will be PC1
target = df1.pop('target')

In [9]:
df1.shape

(303, 13)

In [10]:
model = PCA(n_components=2)
model.fit(df1)
model.transform(df1)

array([[ 6.24110729e-01,  2.32127028e+00],
       [-4.55987975e-01, -9.57350982e-01],
       [-1.82880491e+00,  4.28847737e-02],
       [-1.71600605e+00, -4.95337323e-01],
       [-3.71356421e-01,  3.01156175e-01],
       [-6.48867460e-01, -3.82882350e-01],
       [-7.26534041e-02,  1.46021954e+00],
       [-1.90592574e+00, -1.15199470e+00],
       [-9.05732769e-01,  1.17802505e+00],
       [-1.42452084e+00,  6.00440468e-02],
       [-8.29249247e-01, -4.31111662e-01],
       [-1.76837052e+00,  6.66082010e-01],
       [-1.73039364e+00, -3.62122452e-01],
       [ 4.78579542e-01, -3.66100880e-01],
       [-1.13904999e+00,  3.31505033e+00],
       [-1.15305728e+00,  3.38842792e-02],
       [-2.05289635e+00,  1.44304375e+00],
       [ 1.24660567e+00,  1.56563220e+00],
       [-1.17898795e+00, -5.93288357e-01],
       [-3.87798996e-01,  2.04509682e+00],
       [-1.09484581e-02, -7.39533549e-01],
       [-1.69288377e+00, -1.05478211e+00],
       [-2.03684479e+00, -9.44816640e-01],
       [ 9.

In [20]:
model.explained_variance_ratio_

array([0.21254053, 0.11820708])

In [30]:
model.explained_variance_ratio_.sum()

0.33074760846179396

In [21]:
model.components_

array([[ 0.31420252,  0.09083783, -0.27460749,  0.18392019,  0.11737503,
         0.07363999, -0.12772792, -0.41649811,  0.36126745,  0.41963899,
        -0.37977222,  0.27326172,  0.22202375],
       [ 0.40614872, -0.37779171,  0.29726609,  0.43818675,  0.36451402,
         0.31743328, -0.22088181,  0.07787618, -0.2631179 , -0.05225497,
         0.04837415,  0.09414721, -0.20072042]])

In [26]:
model2 = PCA()
model2.fit(df1)
model2.transform(df1)

array([[ 0.62411073,  2.32127028,  2.47467255, ..., -0.55811461,
         0.40407485,  0.42022097],
       [-0.45598798, -0.95735098,  1.1395948 , ..., -0.4921327 ,
         0.23225951,  0.27427359],
       [-1.82880491,  0.04288477, -0.45222878, ...,  0.36372499,
         0.17797717, -1.10955334],
       ...,
       [ 2.45900545,  0.47826191,  2.20821632, ..., -1.46340968,
         0.91844747, -0.75068625],
       [ 1.76275536, -2.33681621,  0.45475258, ...,  0.376824  ,
        -0.07554132,  0.34956711],
       [-0.86005677,  1.06851556, -0.69007429, ...,  0.08023982,
         0.31320761,  1.17838479]])

In [29]:
model2.explained_variance_ratio_

array([0.21254053, 0.11820708, 0.09406418, 0.09085735, 0.07861281,
       0.07461661, 0.06636692, 0.05968811, 0.05530196, 0.04781309,
       0.04077729, 0.03254941, 0.02860467])

In [31]:
model3 = PCA(n_components=0.9)
model3.fit(df1)
model3.transform(df1)

array([[ 0.62411073,  2.32127028,  2.47467255, ..., -0.6389401 ,
         0.93265088, -0.55811461],
       [-0.45598798, -0.95735098,  1.1395948 , ...,  1.24182435,
         1.16568065, -0.4921327 ],
       [-1.82880491,  0.04288477, -0.45222878, ...,  1.29320203,
        -1.14706565,  0.36372499],
       ...,
       [ 2.45900545,  0.47826191,  2.20821632, ...,  0.25210999,
        -0.9108683 , -1.46340968],
       [ 1.76275536, -2.33681621,  0.45475258, ..., -0.35298085,
        -0.96618535,  0.376824  ],
       [-0.86005677,  1.06851556, -0.69007429, ...,  0.8017775 ,
        -1.05850277,  0.08023982]])

In [33]:
model3.explained_variance_ratio_

array([0.21254053, 0.11820708, 0.09406418, 0.09085735, 0.07861281,
       0.07461661, 0.06636692, 0.05968811, 0.05530196, 0.04781309,
       0.04077729])